                                                                                                                
# Configure a default setup of Home Assistant (frontend, api, etc)                                                
default_config:                                                                                                   
                                                                                                                  
# Text to speech                                                                                                  
tts:                                                                                                              
  - platform: google_translate                                                                                    
                                                                                                                  
group: !include groups.yaml                                                                                       
automation: !include automations.yaml                                                                             
script: !include scripts.yaml                                                                                     
scene: !include scenes.yaml                                                                                       
                                                                                                                  
http:                                                                                                             
  api_password: !secret api_password                                                                              
  base_url: https://{your_synology_domain}.synology.me:15000                                                                     
  ip_ban_enabled: true                                                                                            
  login_attempts_threshold: 5                                                                                     
~                              